name: studies_project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  signals: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  lint_staged: ^0.5.1
  husky: ^0.1.7
  derry: ^1.5.0

flutter:
  uses-material-design: true

lint_staged:
  "lib/**.dart": dart fix --apply && dart format --fix && dart analyze

scripts: derry.yaml
